apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: aggregate-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "aggregate router"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
      aggregateType:
          title: .
          description: .
          type: string
          default: text/xml
      completionSize:
          title: .
          description: .
          type: string
          default: 3
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: Aggregate-Type
              constant: "{{aggregateType}}"
          - aggregate:
              aggregation-strategy: "#class:org.assimbly.dil.blocks.beans.enrich.AggregateStrategy"
              completionSize: "{{completionSize}}"
          - to:
              uri: "kamelet:sink"