apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: aleris-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "aleris action"
    description: |-
      Aleris component
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "aleris:{{path}}"