apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: amazon-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "amazon action"
    description: |-
      Amazon component
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "amazon:{{path}}?{{options}}"