apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: csvtoxml-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "csvtoxml action"
    description: |-
      Converts CSV to XML
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      delimiter:
          title: Delimiter
          description: Delimiter
          type: string
          default: ","
      useheader:
          title: Use Header
          description: Wether to use header or not
          type: string
          default: "yes"
      encoding:
        title: Encoding
        description: Type of encoding
        type: string
        default: "UTF-8"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - unmarshal:
              csv:
                delimiter: "{{delimiter}}"
                useHeader: "{{useheader}}"
          - to:
              uri: "csvtoxml://?encoding={{encoding}}"
          - to:
              uri: "kamelet:sink"