apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: delete-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "delete source"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "rest:delete:{{path}}?{{options}}"
        steps:
          - to:
              uri: "kamelet:sink"