apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: edifacttoxml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "edifacttoxml sink"
    description: |-
      Converts Edifact to XML
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:edifact:marshal?{{options}}"