apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: editoxml-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "editoxml action"
    description: |-
      Convert EDI to XML
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:edi:marshal?{{options}}"
          - to:
              uri: "kamelet:sink"