apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: enrich-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "enrich router"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
          title: 
          description: .
          type: string
      enrichType:
          title: .
          description: .
          type: string
          default: text/xml
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: flowId
              constant: "{{path}}"
          - set-property:
              name: action
              constant: "stopflow"
          - enrich:
              resource-uri: "{{out_rule}}"
              aggregation-strategy: "#class:org.assimbly.dil.blocks.beans.enrich.EnrichStrategy"
          - to:
              uri: "kamelet:sink"