apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: formtoxml-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "formtoxml action"
    description: |-
      Convert Form to XML
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "formtoxml://?{{options}}"
          - to:
              uri: "kamelet:sink"