apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: get-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "get sink"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:trace:{{path}}?{{options}}"