apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: groovy-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "groovy action"
    description: |-
      Apply Groovy script
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "sandbox://groovy?script=RAW({{path}})"
          - to:
              uri: "kamelet:sink"