apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: hl7xml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "hl7xml sink"
    description: |-
      Convert HL7 to XML
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "bean:XmlToHl7Converter"
          - to:
              uri: "mllp:{{path}}"