apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: https-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "https sink"
    description: |-
      Sends HTTP Requests
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path of the URL
          type: string
      options:
          title: Options
          description: options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "https:{{path}}?{{options}}"
