apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: https-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "https action"
    description: |-
      Sends HTTP Requests
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      uri:
        title: URI
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "{{uri}}"
          - to:
              uri: "kamelet:sink"