apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: java-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "java script"
    description: |-
      Runs java code (through joor)
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              joor: "{{path}}"
          - to:
              uri: "kamelet:sink"