apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: javascript-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "javascript sink"
    description: |-
      Apply Javascript
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              js: "{{path}}"