apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: joor-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "joor script"
    description: |-
      Runs java code (through joor)
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        set-body:
          joor: "{{path}}"
        steps:
          - to:
              uri: "kamelet:sink"