apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: link-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "link router"
    description: |-
      Links steps
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - recipient-list:
              constant: "{{out_list}}"
