apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: options-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "options action"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:options:{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"