apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: oriflame-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "oriflame sink"
    description: |-
      Oriflame component
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "oriflame:{{path}}?{{options}}"