apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: queuethrottle-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "queuethrottle sink"
    description: |-
      Throttle messages on an ActiveMQ queue
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      timePeriod:
        title: Time Period
        description: Time Period
        type: string
        default: 5000
      maxRequests:
        title: Max Requests
        description: Max requests
        type: string
        default: 1
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: AssimblyQueueName
              constant: "{{path}}"
          - process:
              ref: "ManageQueueMessageCheckerFlowProcessor"
          - filter:
              simple: "${exchangeProperty.AssimblyQueueHasMessages} == true"
          - loop:
              constant: "{{maxRequests}}"
              steps:
                - set-property:
                    name: Enrich-Type
                    constant: "application/override"
                - set-property:
                    name: AssimblyAggregateNoExceptionOnNull
                    simple: "true"
                - poll-enrich:
                    constant: "activemq:{{path}}"
                    timeout: "{{timePeriod}}"
                    aggregationStrategy: "CurrentEnrichStrategy"
                - filter:
                    simple: "${body} != null"
                    steps:
                      - remove-headers:
                          pattern: "fireTime|jobRunTime|nextFireTime|previousFireTime|refireCount|scheduledFireTime|triggerGroup|triggerName|jobDetail|jobInstance|mergedJobDataMap|result|scheduler|trigger"
                          excludePattern: "breadcrumbId"