apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: queuethrottle-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "queuethrottle action"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      timePeriod:
          title: .
          description: .
          type: string
          default: 5000
      maxRequests:
          title: .
          description: .
          type: string
          default: 1
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"