apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: queuethrottle-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "queuethrottle action"
    description: |-
      Throttles messages on an ActiveMQ queue
    type: object
    properties:
      timePeriod:
          title: Time Period
          description: Time Period
          type: string
          default: 5000
      messages:
          title: Messages
          description: Max number of messages
          type: string
          default: 1
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: AssimblyQueueName
              constant: "{{path}}"
          - process:
              ref: "QueueMessageChecker"
          - filter:
              simple: "${exchangeProperty.AssimblyQueueHasMessages} == true"
          - loop:
              constant: "{{messages}}"
              steps:
                - setProperty:
                    name: Enrich-Type
                    constant: "application/override"
                - setProperty:
                    name: AssimblyAggregateNoExceptionOnNull
                    simple: "true"
                - pollEnrich:
                    constant: "activemq:{{path}}"
                    timeout: "{{timePeriod}}"
                    aggregationStrategy: "CurrentEnrichStrategy"
                - filter:
                    simple: "${body} != null"
                    steps:
                      - removeHeaders:
                          pattern: "fireTime|jobRunTime|nextFireTime|previousFireTime|refireCount|scheduledFireTime|triggerGroup|triggerName|jobDetail|jobInstance|mergedJobDataMap|result|scheduler|trigger"
                          excludePattern: "breadcrumbId"
          - to:
              uri: "kamelet:sink"