apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: rabbitmq-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "rabbitmq action"
    description: |-
      Sends messages to RabbitMQ
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: excludedHeader_breadcrumbId
              simple: "${header.breadcrumbId}"
          - remove-header:
              name: "breadcrumbId"
          - set-header:
              name: CamelRabbitmqDeliveryMode
              constant: "2"
          - toD:
              uri: "rabbitmq:{{path}}?{{options}}"
          - set-header:
              name: breadcrumbId
              simple: "${exchangeProperty.excludedHeader_breadcrumbId}"
          - remove-property:
              name: "excludedHeader_breadcrumbId"
          - to:
              uri: "kamelet:sink"