apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: removecookie-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "removecookie action"
    description: |-
      Sets a browser cookie
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
          default: AssimblyCookie
      domain:
        title: Domain
        description: Domain
        type: string
        default: "org.assimbly"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "bean://flowCookieStore?method=removeStringAsCookie(${exchange},'{{path}}','{{domain}}')"
          - to:
              uri: "kamelet:sink"