apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: removeheaders-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "removeheaders sink"
    description: |-
      Remove headers from message
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      excludePatterns:
        title: Exclude Pattern
        description: Exclude Pattern
        type: string
        default: 0
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - remove-headers:
              pattern: "{{path}}"
              exclude-pattern: "{{excludePattern}}"