apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: replaceinpdf-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "replaceinpdf action"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: 
          description: .
          type: string
      options:
          title: 
          description: .
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"