apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setbodybyheader-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbodybyheader sink"
    description: |-
      Set body from header
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-body:
              header: "{{path}}"