apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setbody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbody sink"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      language:
          title: Language
          description: Expression language
          type: string
          default: constant
      path:
          title: Path
          description: The body
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: assimbly.body
              constant: "{{path}}"
          - set-property:
              name: assimbly.language
              constant: "{{language}}"
          - process:
              ref: "SetBodyProcessor"