apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setbody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbody sink"
    description: |-
      to do
    type: object
    properties:
      language:
        title: Set Body
        description: Set Body of a message
        type: string
        default: constant
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: assimbly.body
              constant: "{{path}}"
          - setProperty:
              name: assimbly.language
              constant: "{{language}}"
          - process:
              ref: "SetBodyProcessor"