apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setheader-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setheader action"
    description: |-
      Set an exchange header
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      value:
        title: Value
        description: Value of header
        type: string
      language:
        title: Language
        description: Expression language to evaluate
        type: string
        default: constant
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - choice:
            when:
              - simple: "'{{language}}' == 'simple'"
                steps:
                  - set-header:
                    name: "{{path}}"
                    simple: "{{value}}"
              - simple: "'{{language}}' == 'xpath'"
                steps:
                  - set-header:
                    name: "{{path}}"
                    xpath: "{{value}}"
              - simple: "'{{language}}' == 'jsonpath'"
                steps:
                  - set-header:
                    name: "{{path}}"
                    jsonpath: "{{value}}"
              - simple: "'{{language}}' == 'groovy'"
                steps:
                  - set-header:
                    name: "{{path}}"
                    groovy: "{{value}}"
            otherwise:
              steps:
                - set-header:
                  name: "{{path}}"
                  consant: "{{value}}"
          - to:
              uri: "kamelet:sink"