apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setheaderbybody-sink
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodybyheader sink"
    description: |-
      Set header from body
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
          default: body
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setHeader:
              name: "{{path}}"
              simple: "${body}"