apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setmessage-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setmessage sink"
    description: |-
      Set message (body and headers)
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      headers:
        title: Headers
        description: Headers
        type: string
        default: 0
      language:
        title: Language
        description: Language
        type: string
        default: constant
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-property:
              name: assimbly.body
              constant: "{{path}}"
          - set-property:
              name: assimbly.language
              constant: "{{language}}"
          - set-property:
              name: assimbly.headers
              constant: "{{headers}}"
          - process:
              ref: "SetBodyProcessor"
          - process:
              ref: "SetHeadersProcessor"
