apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setoauth2token-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setoauth2token action"
    description: |-
      Set oAuth2token
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "setoauth2token://?{{options}}"
          - to:
              uri: "kamelet:sink"