apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setpattern-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setpattern action"
    description: |-
      Set the exchange pattern
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: 
          description: .
          type: string
      pattern:
          title: Pattern
          description: Pattern to use (inOnly, inOut, inOptionalOut)
          type: string
          default: InOnly
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setExchangePattern: "{{pattern}}"
          - to:
              uri: "kamelet:sink"