apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: simplereplace-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "simplereplace sink"
    description: |-
      Replace simple expression in the message body
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:simple-replace:unmarshal"