apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: simple-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "simple script"
    description: |-
      Applies simple expression to message body
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              simple: "{{path}}"
          - to:
              uri: "kamelet:sink"