apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: simplereplace-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "simplereplace action"
    description: |-
      Replace simple expression in the message body
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:simple-replace:unmarshal"
          - to:
              uri: "kamelet:sink"