apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: split-xpath-router
  labels:
    camel.apache.org/kamelet.type: "xpath-router"
spec:
  definition:
    title: "split xpath-router"
    description: |-
      Splits message by xpath
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
      expression:
          title: 
          description: .
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - split:
              xpath: "{{expression}}"
              steps:
                - set-header:
                    name: CamelSplitIndex
                    simple: ${exchangeProperty.CamelSplitIndex}
                - set-header:
                    name: CamelSplitSize
                    simple: ${exchangeProperty.CamelSplitSize}
                - set-header:
                    name: CamelSplitComplete
                    simple: ${exchangeProperty.CamelSplitComplete.toString().trim()}
                - to: "{{out_rule}}"
          - choice:
              when:
                - simple: "{{out}}!='mock:0'"
                  steps:
                    - to:
                        uri: "kamelet:sink"