apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: texttobase64-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "texttobase64 action"
    description: |-
      Convert text to base64 string
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - marshal:
              base64: {}
          - to:
              uri: "kamelet:sink"