apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: trace-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "trace action"
    description: |-
      REST Endpoint for the trace method
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:trace:{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"