apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: trace-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "trace sink"
    description: |-
      REST Endpoint for the trace method
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
          title: Options
          description: Endpoint options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:trace:{{path}}?{{options}}"