apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: univocity-csv-action
  labels:
    camel.apache.org/kamelet.type: "csv-action"
spec:
  definition:
    title: "univocity csv-action"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:univocityCsv:{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"