apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: unzip-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "unzip sink"
    description: |-
      Unzips a message
    type: object
    properties:
      usingIterator:
        title: Using Iterator
        description: .
        type: string
        default: true
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:checkedZipFileDataFormat:unmarshal?usingIterator={{usingIterator}}"