apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: unzip-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "unzip action"
    description: |-
      Unzips a message
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      usingIterator:
        title: Using Iterator
        description: .
        type: string
        default: true
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:checkedZipFileDataFormat:unmarshal?usingIterator={{usingIterator}}"
          - to:
              uri: "kamelet:sink"