apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: velocity-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "velocity action"
    description: |-
      Applies a velocity template
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: 
          description: .
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-header:
              name: CamelVelocityTemplate
              simple: "{{path}}"
          - to:
              uri: "velocity:generate?allowTemplateFromHeader=true"
          - to:
              uri: "kamelet:sink"