apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: xmltojson-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xmltojson action"
    description: |-
      Convert XML to JSON
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
          title: options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:custom-xmljson:marshal?{{options}}"
          - to:
              uri: "kamelet:sink"