apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: xmltoexcel-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xmltoexcel sink"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      orderHeaders:
          title: .
          description: .
          type: string
          default: UNORDERED
      excelFormat:
          title: .
          description: .
          type: string
          default: XLSX
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"