apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: xmltocsv-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xmltocsv action"
    description: |-
      to do
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      orderHeaders:
          title: .
          description: .
          type: string
          default: UNORDERED
      quoteFields:
          title: .
          description: .
          type: string
          default: ALL_FIELDS
      delimiter:
          title: .
          description: .
          type: string
          default: LA==
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xmltocsv://?includeHeader={{includeHeader}}&includeIndexColumn={{includeIndexColumn}}&indexColumnName={{indexColumnName}}&orderHeaders={{orderHeaders}}&quoteFields={{quoteFields}}&delimiter=RAW({{delimiter}})&lineSeparator=RAW({{lineSeparator}})"
          - to:
              uri: "kamelet:sink"