apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: xslt-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "xslt script"
    description: |-
      Apply XSLT on message
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xslt-saxon:{{path}}?saxonExtensionFunctions=#uuid-function"
          - to:
              uri: "kamelet:sink"