apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: xslt-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xslt sink"
    description: |-
      Apply XSLT on message
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      options:
          title: 
          description: .
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xslt-saxon:{{path}}?saxonExtensionFunctions=#uuid-function"