apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: zip-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "zip sink"
    description: |-
      Zips a message
    type: object
    properties:
      preservePathElements:
        title: Preserve Path Elements
        description: .
        type: string
        default: true
      usingIterator:
        title: Using Iterator
        description: .
        type: string
        default: true
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:zipFileDataFormat:marshal?usingIterator={{usingIterator}}&amp;preservePathElements={{preservePathElements}}"