name: Release Snapshots

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 1 * * *'

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.runtime
            org.assimbly.dil
            org.assimbly.broker
            org.assimbly.broker-rest
            org.assimbly.integration
            org.assimbly.integration-rest

  call-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      branch: 'develop'
