name: Finish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:

  create-new-branch:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          repository: assimbly/runtime
          ref: "develop"
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: create a new branch
        run: |
          git fetch --all          
          git config --global push.autoSetupRemote true
          git config --local user.email "raymondmeester@gmail.com"
          git config --local user.name "skin27"
          git checkout -b ${{inputs.milestone}}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          repository: assimbly/runtime
          branch: ${{ inputs.milestone }}
          force_with_lease: true

  call-update-version:
    needs: create-new-branch
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: "${{ inputs.milestone }}"
      milestone: "${{ inputs.milestone }}"

  merge-new-branch:

    needs: call-update-version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          repository: assimbly/runtime
          ref: main
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: merge new branch
        run: |
          git fetch --all          
          git config --global push.autoSetupRemote true
          git config --local user.email "raymondmeester@gmail.com"
          git config --local user.name "skin27"
          git merge origin/${{inputs.milestone}}
          git push 

  delete-old-packages:

    needs: merge-new-branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: assimbly
          type: maven
          keep: 0
          token: ${{ secrets.MAVEN_TOKEN }}
          semver-pattern: ${{ inputs.milestone }}
          names: |
            org.assimbly.runtime
            org.assimbly.integration-rest
            org.assimbly.integration
            org.assimbly.dil
            org.assimbly.broker-rest
            org.assimbly.broker    

  call-release-jars:
    needs: delete-old-packages
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      branch: 'main'

