name: Publish Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'snapshots-tests'

jobs:
  delete_older_snapshots:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.runtime
            org.assimbly.integration-rest
            org.assimbly.integration
            org.assimbly.dil
            org.assimbly.broker-rest
            org.assimbly.broker

  publish_runtime_snapshot:
    needs: [delete_older_snapshots]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Update POM Version
        env:
          VERSION: 4.0.0-SNAPSHOT
        run: |
            echo "Updating to version: ${VERSION}"
            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${VERSION}
            mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${VERSION}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}